### ISSUE TITLE
Dev mode crash

### ISSUE THREAD

**Issue by sbot50** [DFOnline/CodeClient#42]
Go to beta (i only tested beta, main probs works too)
Go onto plot
Do /dev
Crash

Probably only happens on plots you have dev on

[16:07:14] [Netty Epoll Client IO #0/INFO]: Switched location: code
[16:07:14] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "dev.dfonline.codeclient.location.Dev.getX()" is null
	at dev.dfonline.codeclient.dev.NoClip.isInDevSpace(NoClip.java:24) ~[transformed-mod-codeclient.i0:0/:?]
	at dev.dfonline.codeclient.dev.NoClip.isIgnoringWalls(NoClip.java:20) ~[transformed-mod-codeclient.i0:0/:?]
	at net.minecraft.class_4603.handler$bjk000$codeclient$inWall(class_4603.java:1016) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4603.method_24225(class_4603.java) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_4603.method_23067(class_4603.java:32) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3172(class_757.java:822) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3188(class_757.java:1137) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_757.method_3192(class_757.java:880) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524) ~[quilt-loader-0.19.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.19.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.19.1.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[16:07:15] [Render thread/INFO]: Stopping worker threads

**Comment by sbot50** [comment]
Seems to only happen if you join a plot in either build or play, if you join a plot in dev you can switch between without crashing

**Comment by GeorgeRNG** [comment]
iirc I fixed this on my other computer but didn't push.
